{
    "name": "Deploy to droplet",
    "on":
    {
        workflow_dispatch: {},
        "issue_comment":
        {
            "types": ["created"],
        },
    },
    "jobs":
    {
        "deploy":
        {
            "if": "github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request != null && contains(github.event.comment.body, '/deploy'))",
            "runs-on": "ubuntu-latest",
            "steps":
            [
                {
                    "name": "Checkout repo",
                    "uses": "actions/checkout@v3"
                },
                {
                    "name": "Set up SSH",
                    "uses": "webfactory/ssh-agent@v0.8.1",
                    "with": 
                    {
                        "ssh-private-key": "${{ secrets.DROPLET_SSH_KEY }}"
                    }
                },
                {
                    "name": "Copy cert key",
                    "run": "echo '${{ secrets.DROPLET_CERT_KEY }}' > ./nginx/ssl/droplet.eipie.io/origin.key"
                },
                {
                    "name": "Copy nginx to VPS",
                    "run": "rsync -avz --delete ./nginx/ ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:~/nginx/"
                },
            ]
        }
    }
}
