{
    "name": "Deploy to droplet",
    "on":
    {
        workflow_dispatch: {},
        "issue_comment":
        {
            "types": ["created"],
        },
    },
    "jobs":
    {
        "deploy":
        {
            "if": "github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request != null && contains(github.event.comment.body, '/deploy'))",
            "runs-on": "ubuntu-latest",
            "steps": [],
        },
    },
}
